<!--TITLE: Catch Exception Command -->
<!-- SUBTITLE: a command in the Error Handling Commands group. -->
[Go To Automation Commands Overview](/automation-commands.md)


# Catch Exception Command


## What does this command do?
This command allows you to define actions that should occur after encountering an error.


## When would I want to use this command?
Use this command when you want to define how your script should behave when an error is encountered.


## Command Parameters
| Parameter Question   	| What to input  	|  Sample Data 	| Remarks  	|
| ---                    | ---               | ---           | ---       |
|Comment Field (Optional)|Optional field to enter a custom comment which could potentially describe this command or the need for this command, if required|I am using this command to ...|Optional|


## Developer/Additional Reference
Automation Class Name: CatchExceptionCommand
Parent Namespace: taskt.Core.Automation.Commands
This page was generated on 06/16/21 10:47 午後


## Help
[Open/Report an issue on GitHub](https://github.com/saucepleez/taskt/issues/new)
[Ask a question on Gitter](https://gitter.im/taskt-rpa/Lobby)
